FROM python:3.11-slim

WORKDIR /app

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_HOME=/opt/poetry

RUN pip install poetry==1.8.2

COPY pyproject.toml ./
RUN poetry install --no-root --only main

COPY client/ ./client/
COPY common/ ./common/

ENTRYPOINT ["python", "-m", "client.client"]
