# Network
DEFAULT_HOST = "0.0.0.0"
DEFAULT_CLIENT_HOST = "127.0.0.1"
DEFAULT_PORT = 4444
CONNECT_TIMEOUT_SEC = 10.0

# Communication
BUFFER_SIZE = 4096
LENGTH_PREFIX_BYTES = 4
MAX_MESSAGE_BYTES = 16 * 1024 * 1024
MAX_RETRIES = 3
RETRY_DELAY = 5
PROTOCOL_VERSION = "1.0"

HANDSHAKE_ACTION = "handshake"
# Temporary wire check; remove when real commands land.
TEST_ACTION = "test"
